
import getCurrentUser from './actions/getCurrentUser'
import ClientOnly from './components/ClientOnly'
import FollowUsers from './components/followUsers/FollowUsers'
import BetModal from './components/modals/bet-modal/BetModal'
import EditProfileModal from './components/modals/EditProfileModal'
import LoginModal from './components/modals/LoginModal'
import RegisterModal from './components/modals/RegisterModal'
import Navbar from './components/navbar/Navbar'
import News from './components/news/News'
import Scoreboard from './components/scoreboard/Scoreboard'
import ToasterProvider from './providers/ToasterProvider'
import './styles/globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body>

        <ClientOnly>
          <ToasterProvider />
          <RegisterModal />
          <LoginModal />
          <BetModal />
          <EditProfileModal />
          <div className='sidebarContainer'>
            <Navbar currentUser={currentUser} />
          </div>

          <div className="gamebarContainer">
            <Scoreboard />
          </div>
          <div className='rightSidebar'>
            {/* <News /> */}
            {/* <FollowUsers /> */}
          </div>
          <div className="mainContainer">
            {children}
          </div>
        </ClientOnly>
      </body>
    </html >
  )
}
